version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: nextchat
      APP_PORT: 3000
      PROXY_AUTH_ADD: "false"

  nextchat:
    image: yidadaa/chatgpt-next-web:latest
    restart: on-failure
    environment:
      - OPENAI_API_KEY=
      - GOOGLE_API_KEY=
      - CODE=
      - BASE_URL=
      - OPENAI_ORG_ID=
      - HIDE_USER_API_KEY=
      - DISABLE_GPT4=
      - ENABLE_BALANCE_QUERY=
      - DISABLE_FAST_LINK=
      - OPENAI_SB=
      - ENABLE_MCP=true
