version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: all-is-cubes
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"

  all-is-cubes:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure