version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: asciiflow
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"

  asciiflow:
    image: pfav/asciiflow:latest
    restart: on-failure